"""instrucao_exercicio_text

Revision ID: 2f76b9f116d6
Revises: 8eaf164adb72
Create Date: 2026-08-17 21:10:24.456522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2f76b9f116d6'
down_revision: Union[str, Sequence[str], None] = '8eaf164adb72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercicios', 'instrucao',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercicios', 'instrucao',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###
