"""ajuste modelo exercicio

Revision ID: 8eaf164adb72
Revises: a6a50feaf206
Create Date: 2026-08-12 20:52:25.656453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8eaf164adb72'
down_revision: Union[str, Sequence[str], None] = 'a6a50feaf206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercicios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_externo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('rotulo', sa.String(length=100), nullable=False),
    sa.Column('grupo_muscular', sa.String(length=50), nullable=False),
    sa.Column('equipamento', sa.String(length=50), nullable=False),
    sa.Column('instrucao', sa.String(length=500), nullable=False),
    sa.Column('gif_url', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_externo')
    )
    op.drop_index(op.f('id_externo'), table_name='exercicos')
    op.drop_table('exercicos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercicos',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('id_externo', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('categoria', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('rotulo', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('grupo_muscular', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('equipamento', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('instrucoes', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('gif_url', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('id_externo'), 'exercicos', ['id_externo'], unique=True)
    op.drop_table('exercicios')
    # ### end Alembic commands ###
