"""criação models treino,treino_exercício, execução e avaliação

Revision ID: a6a50feaf206
Revises: ec915e142397
Create Date: 2026-08-10 21:05:01.943418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6a50feaf206'
down_revision: Union[str, Sequence[str], None] = 'ec915e142397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliacoes_fisicas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('data_avaliacao', sa.DateTime(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('altura', sa.Float(), nullable=False),
    sa.Column('percentual_gordura', sa.Float(), nullable=False),
    sa.Column('massa_gorda', sa.Float(), nullable=False),
    sa.Column('massa_muscular', sa.Float(), nullable=False),
    sa.Column('imc', sa.Float(), nullable=False),
    sa.Column('gordura_visceral', sa.Float(), nullable=False),
    sa.Column('agua_corporal', sa.Float(), nullable=False),
    sa.Column('taxa_metabolica_basal', sa.Float(), nullable=False),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execucoes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('treino_exercicio_id', sa.String(length=36), nullable=False),
    sa.Column('data_execucao', sa.DateTime(), nullable=False),
    sa.Column('carga', sa.Integer(), nullable=False),
    sa.Column('series_realizadas', sa.Integer(), nullable=False),
    sa.Column('repeticoes_realizadas', sa.Integer(), nullable=False),
    sa.Column('tempo_descanso_real', sa.Integer(), nullable=False),
    sa.Column('duracao_execucao', sa.Integer(), nullable=False),
    sa.Column('calorias_queimadas', sa.Integer(), nullable=False),
    sa.Column('frequencia_cardiaca_media', sa.Integer(), nullable=False),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treino_exercicios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('treino_id', sa.String(length=36), nullable=False),
    sa.Column('exercicio_id', sa.String(length=36), nullable=False),
    sa.Column('series', sa.Integer(), nullable=False),
    sa.Column('repeticoes', sa.Integer(), nullable=False),
    sa.Column('tempo_descanso', sa.Integer(), nullable=False),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treinos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('dia_da_semana', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treinos')
    op.drop_table('treino_exercicios')
    op.drop_table('execucoes')
    op.drop_table('avaliacoes_fisicas')
    # ### end Alembic commands ###
